# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jahsa Coleman
tagline:          'some sort of web presence'
description:      'Follow me on <a href="http://twitter.com/smashtic" target="_blank">Twitter</a>' 
url:              jahsa.co

author:
  name:           'Jahsa Coleman'
  url:            https://twitter.com/smashtic

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jahsa
