# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jahsa
tagline:          'wip'
description:      'still workin'
url:              http://lanyon.getpoole.com

author:
  name:           'Jahsa Coleman'
  url:            https://twitter.com/smashtic

paginate:         5

# Custom vars
#version:          1.0.0

github:
  repo:           https://github.com/jahsa
